### ISSUE TITLE
"AttributeError: 'PikaStack' object has no attribute 'pop'" when dividing

### ISSUE THREAD

**Issue by Kyle-Coughlin** [joelsmithjohnson/pikachu-interpreter#1]
I am not sure if this is an error with your interpreter or with the language, but I ran into the following error when testing out pikachu arithmetic using your compiler.  I was using the command "pikachu pi pikachu" with 2 integers provided as command line args, which should divide the two integers on the stack.  I was able to perform addition, subtraction, and multiplication just fine.  I was performing it with 2 command parameters, and their values did not matter.

Edit to add: this is on a windows 10 64-bit machine.

Full Traceback:

Traceback (most recent call last):
  File "C:\Users\lilkc\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\lilkc\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lilkc\Documents\Temple 2019 Spring\pikachu-interpreter-master\pikachu\__main__.py", line 20, in <module>
    run(fileName, args)
  File "C:\Users\lilkc\Documents\Temple 2019 Spring\pikachu-interpreter-master\pikachu\interpreter.py", line 77, in run
    tStack.DIV()
  File "C:\Users\lilkc\Documents\Temple 2019 Spring\pikachu-interpreter-master\pikachu\stack.py", line 87, in DIV
    a = self.pop()
AttributeError: 'PikaStack' object has no attribute 'pop'

**Comment by Kyle-Coughlin** [comment]
I forgot to mention that this is on a windows-10 64 bit machine, if that information is relevant.

**Comment by joelsmithjohnson** [comment]
Just made some changes. It was a simple mistake. You should be all good to go now. let me know if the problem is fixed.

**Comment by Kyle-Coughlin** [comment]
Thank you,  your code now works fine.  Gotta love forgetting a pair of
parentheses!
